name: flutterexercise
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # http
  retrofit: ^1.3.4
  dio: ^3.0.9
  flutter_stetho: ^0.5.2

  # logger
  logger: ^0.9.1

  # data utility
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  json_serializable: ^3.3.0

  # lint
  pedantic: ^1.9.0

  # http
  retrofit_generator: ^1.3.7
flutter:
  uses-material-design: true
